### ISSUE TITLE
Add options for CC licenses with NC and ND to CKAN

### ISSUE THREAD

**Issue by gimmemochi** [OpenDevelopmentMekong/ckan-2.3#4]
@acorbi @prustar I'm not sure if there's a document somewhere describing why we decided to only provide license options we currently have for CKAN record -- I'm wondering whether it's intentional to not list CC licenses with NC and ND on CKAN? Some NGOs publish their publications with CC BY-NC-SA or CC BY-NC-ND. MRLG is an example. See: http://mrlg.org/resources/customary-tenure-in-the-mekong-region-workshop-outcomes/

Should we consider other licenses to be added? 

Consider the [following](https://en.wikipedia.org/wiki/Creative_Commons_license) (except BY and BY-SA which we already have as options)
<img width="581" alt="screen shot 2017-06-08 at 4 48 06 pm" src="https://user-images.githubusercontent.com/6489398/26950052-58f4fe1e-4c6a-11e7-9e89-e33804e5df00.png">

**Comment by acorbi** [comment]
moving to https://github.com/OpenDevelopmentMekong/ckanext-odm_nav/issues/85
